# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 19:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models, connection
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionTestModelPKAutoInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKBigInt',
            fields=[
                ('id', models.BigIntegerField(default=9223372036854775807, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKDecimal',
            fields=[
                ('id', models.DecimalField(decimal_places=4, default=Decimal('1234.2401'), max_digits=19, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKFloat',
            fields=[
                ('id', models.FloatField(default=1234.234, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKGuid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKString',
            fields=[
                ('id', models.CharField(default='NEW_ID', max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKStringLarge',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKText',
            fields=[
                ('id', models.TextField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ) if connection.vendor != "mysql"
        else migrations.CreateModel(
            name='ReversionTestModelPKText',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        )
    ]
