# Generated by Django 4.1.7 on 2023-03-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='content_type',
            field=models.ForeignKey(
                db_constraint=False,
                help_text='Content type of the model under version control.',
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AlterField(
            model_name='version',
            name='revision',
            field=models.ForeignKey(
                db_constraint=False,
                help_text='The revision that contains this version.',
                on_delete=django.db.models.deletion.CASCADE,
                to='reversion.revision',
            ),
        ),
    ]
