# Generated by Django 4.2.11 on 2024-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_archived',
            field=models.BooleanField(help_text='True when serialized data is stored in file instead of db.', null=True),
        ),
    ]
