# Generated by Django 5.0.1 on 2024-01-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('-pk',), 'verbose_name': 'revision', 'verbose_name_plural': 'revisions'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-pk',), 'verbose_name': 'version', 'verbose_name_plural': 'versions'},
        ),
    ]
