# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-03 16:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0003_auto_20160601_1600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='version',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
