# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0004_auto_20150811_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('comment', models.TextField(blank=True, help_text='A text comment on this revision.', verbose_name='comment')),
            ],
            options={
                'verbose_name_plural': 'audit logs',
                'ordering': ('-created_at',),
                'verbose_name': 'audit log',
            },
        ),
        migrations.AlterField(
            model_name='version',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Created'), (2, 'Changed'), (3, 'Deleted'), (4, 'Follow'), (5, 'Audit')], verbose_name='version type'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='versions',
            field=models.ManyToManyField(to='reversion.Version', verbose_name='versions'),
        ),
    ]
