# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reversion', '0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='user',
            field=models.UUIDField(blank=True, null=True,
                                   help_text='The UUID of the user who created this revision.',
                                   verbose_name='user'),
        ),
    ]
