# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0005_auto_20160518_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
