# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_auto_20141216_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='db',
            field=models.CharField(default='default', help_text='The database the model under version control is stored in.', max_length=191),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='object_id',
            field=models.CharField(help_text='Primary key of the model under version control.', max_length=191),
        ),
        migrations.RemoveField(
            model_name='version',
            name='object_id_int',
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('object_id', 'content_type', 'db', 'revision')]),
        ),
    ]
