# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0003_auto_20160531_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='db',
            field=models.CharField(default='default', help_text='The database the model under version control is stored in.', max_length=191),
            preserve_default=False,
        ),
    ]
