# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-03 16:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionTestModelPKAutoInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKBigInt',
            fields=[
                ('id', models.BigIntegerField(default=9223372036854775807, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKDecimal',
            fields=[
                ('id', models.DecimalField(decimal_places=4, default=Decimal('1234.2401'), max_digits=19, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKFloat',
            fields=[
                ('id', models.FloatField(default=1234.234, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKGuid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReversionTestModelPKString',
            fields=[
                ('id', models.CharField(default='NEW_ID', max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InlineTestChildModelProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('test_app.inlinetestchildmodel',),
        ),
        migrations.CreateModel(
            name='InlineTestParentModelProxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('test_app.inlinetestparentmodel',),
        ),
    ]
