# Generated by Django 2.2.12 on 2020-08-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelWithNaturalKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='v1', max_length=191)),
            ],
        ),
        migrations.AlterField(
            model_name='testmodelnestedinline',
            name='nested_inline_name',
            field=models.CharField(default='v1', max_length=191),
        ),
        migrations.CreateModel(
            name='TestModelInlineByNaturalKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.TestModelWithNaturalKey')),
            ],
        ),
    ]
